### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by d0gf4rt** [ProjectOpenSea/opensea-erc1155#37]
cloning this repo and just trying to deploy straight up per the instructions throws this error:

```
hook@cryptodev:/opt/asdf/delme/opensea-erc1155$ yarn truffle migrate --network rinkeby
yarn run v1.22.10
$ /opt/asdf/delme/opensea-erc1155/node_modules/.bin/truffle migrate --network rinkeby

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



/opt/asdf/delme/opensea-erc1155/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358
                callback(err);
^
Error: Callback was already called.
    at /opt/asdf/delme/opensea-erc1155/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:1
    at WriteStream.<anonymous> (/opt/asdf/delme/opensea-erc1155/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358:1)
    at WriteStream.emit (events.js:315:20)
    at WriteStream.destroy (/opt/asdf/delme/opensea-erc1155/node_modules/truffle/build/webpack:/node_modules/level-ws/level-ws.js:140:1)
    at finish (internal/streams/writable.js:670:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by d0gf4rt** [comment]
apparently this may be a node14 issue? first time i ever had any issue with node14 https://github.com/trufflesuite/truffle/issues/3008

**Comment by d0gf4rt** [comment]
adding `skipDryRun: true` fixes this if anyone else comes across this issue. 

thanks
